# Generated by Django 6.0.5 on 2026-05-07 11:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_user_uuids(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    for user in CustomUser.objects.filter(uuid__isnull=True):
        user.uuid = uuid.uuid4()
        user.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_card',
            field=models.FileField(blank=True, null=True,
                                   upload_to='business_cards/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='deactivated_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(populate_user_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
